// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
)

type Request struct {
	ID        int64
	Method    sql.NullString
	Path      string
	Headers   string
	Query     string
	Body      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
