// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"
	"database/sql"
)

const getRequestsCount = `-- name: GetRequestsCount :one
SELECT COUNT(*) FROM requests
`

func (q *Queries) GetRequestsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRequestsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertRequest = `-- name: InsertRequest :exec
INSERT INTO requests (method, path, headers, query, body)
VALUES (?, ?, ?, ?, ?)
`

type InsertRequestParams struct {
	Method  sql.NullString
	Path    string
	Headers string
	Query   string
	Body    string
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertRequest,
		arg.Method,
		arg.Path,
		arg.Headers,
		arg.Query,
		arg.Body,
	)
	return err
}
